import type { Metadata } from "next";
import { Toaster } from "sonner";

import ClerkProvider from "@/components/Providers/ClerkProvider";
import FirebaseSyncProvider from "@/components/Providers/FirebaseSyncProvider";
import Header from "@/components/Header";
import { ThemeProvider } from "@/components/Providers/ThemeProvider";

import "./globals.css";

export const metadata: Metadata = {
  title: "TeraStore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="flex min-h-screen flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ClerkProvider>
            <FirebaseSyncProvider>
              <Header />
              <Toaster
                position="bottom-right"
                richColors
                expand={true}
                visibleToasts={5}
                toastOptions={{
                  classNames: {
                    toast: "border-none!",
                    error: "bg-red-400! text-white!",
                    success: "bg-green-400! text-white!",
                  },
                }}
              />

              {children}
            </FirebaseSyncProvider>
          </ClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
